import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Verso",
  icons: {
    icon: [{ url: "logo.png", type: "image/png" }],
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Image
          className="absolute top-0 left-0 z-[-2] h-full w-full"
          src="/background-v1.svg"
          alt="main background"
          fill
        />
        <Image
          className="absolute top-0 left-0 z-[-1] h-full w-full object-cover brightness-115 contrast-108"
          src="/background-v2.svg"
          alt="main background"
          fill
        />
        {children}
      </body>
    </html>
  );
}
